#pragma once

#define DEBUGMODE 1

#ifdef DEBUGMODE
	#define DEBUGMODE_PRINT_EMANAGER 0
	#define DEBUGMODE_PRINT_FUNCS 0
	#define DEBUGMODE_PRINT_FPS 1
	#define DEBUGMODE_PRINT_INPUTS 0
	#define DEBUGMODE_PRINT_SR_INPUTS 0
	#define DEBUGMODE_PRINT_STATE 0
	#define DEBUGMODE_PRINT_ANIM 0
#else
	#define DEBUGMODE_PRINT_EMANAGER 0
	#define DEBUGMODE_PRINT_FUNCS 0
	#define DEBUGMODE_PRINT_FPS 0
	#define DEBUGMODE_PRINT_INPUTS 0
	#define DEBUGMODE_PRINT_SR_INPUTS 0
	#define DEBUGMODE_PRINT_STATE 0
	#define DEBUGMODE_PRINT_ANIM 0
#endif // DEBUGMODE